site_name: ftm-analyze
site_url: https://docs.investigraph.dev/lib/ftm-analyze
repo_url: https://github.com/dataresearchcenter/ftm-analyze
nav:
  - Intro: index.md
  - Features:
    - ner.md
    - annotate.md
  - In depth:
    - pipeline.md
    - extraction.md
  - Reference:
    - reference/cli.md
    - reference/settings.md
  - Builds:
    - docker.md
theme:
  name: material
  logo: https://cdn.investigativedata.org/style/logos/darc/svg/DARC-Logo-RGB-Horizontal-Neg.svg
  favicon: https://cdn.investigativedata.org/style/logos/darc/favicon.ico
  custom_dir: docs/overrides
  palette:
    - media: "(prefers-color-scheme)"
      scheme: slate
      toggle:
        icon: lucide/sun
        name: Switch to light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: lucide/moon
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: lucide/sun
        name: Switch to light mode
  features:
    - navigation.instant
    - navigation.tracking
    - navigation.sections
    # - navigation.footer
    - toc.follow
    - content.code.copy
extra_css:
  - https://dataresearchcenter.github.io/zensical-theme-darc/stylesheets/darc-zensical.css
extra_javascript:
  - https://unpkg.com/mermaid@10/dist/mermaid.min.js
extra:
  logo_light: https://cdn.investigativedata.org/style/logos/darc/svg/DARC-Logo-RGB-Horizontal-Pos.svg
  social:
    - icon: lucide/mail
      link: mailto:hi@dataresearchcenter.org
    - icon: lucide/globe
      link: https://dataresearchcenter.org
    - icon: simple/github
      link: https://github.com/openaleph/ftm-analyze
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/company/dataresearchcenter/
markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.details
  - admonition
  - pymdownx.tasklist:
      custom_checkbox: true
plugins:
  - search
  - autorefs
